name: Ranch Watch
on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:
    inputs:
      test:
        description: "Send a test message"
        required: false
        default: "false"
      dump_all:
        description: "Post a full snapshot of current businesses and properties"
        required: false
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_TEST: ${{ github.event.inputs.test }}
          POST_ALL: ${{ github.event.inputs.dump_all }}
        run: python monitor.py

      - name: Commit state updates (if any)
        run: |
          git config user.name "ranch-bot"
          git config user.email "ranch-bot@users.noreply.github.com"
          git add state/*.json
          git diff --cached --quiet || git commit -m "Update seen items $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push

